version: "3"

services:

  lib2movedb:
      image: mysql:5.7
      volumes:
          - ./docker/database:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lib2move

  lib2move:
      image: webdevops/php-nginx:latest
      build: 
        context: ./
        dockerfile: ./Dockerfile
      volumes:
          - ./:/app
      working_dir: /app
      env_file: .env
      ports:
          - "8011:80"
      depends_on:
          - lib2movedb
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          PHP_DATE_TIMEZONE: "Europe/Paris"
          PHP_DISPLAY_ERRORS: 1
      # command: bash -c "npm run encore dev --watch"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - lib2movedb
      ports:
          - "8012:80"
      environment:
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: lib2movedb